name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  verify:
    uses: ./.github/workflows/python-tests.yml

  publish:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        
      - name: Install dependencies
        run: make install
        
      - name: Build package
        run: make build
        
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
